version: '3.2'

networks:
    neo4j:
        driver: bridge

services:
    client:
        build:
            context: .
            dockerfile: Dockerfile
        networks:
            - neo4j
        volumes:
            - .:/opt/project
        depends_on:
            - neo4j
        restart: always
        expose:
            - 9000
        environment:
            - NEO4J_USER=neo4j
            - NEO4J_PASSWORD=test
            - NEO4J_HOST=neo4j
            - NEO4J_SCHEMA=http
            - NEO4J_PORT=7474
    neo4j:
        networks:
            - neo4j
        image: neo4j:3.5
        ports:
            - "7474:7474"
            - "7687:7687"
        expose:
            - 7474
            - 7687
            - 6362
        environment:
            - NEO4J_AUTH=neo4j/test
